# * Key-value pairs that do not appear here will be set to default values defined in the dataclasses.
# * Key names and value types will be verified.

asr:
  model_name: 'large-v3'

css:
  segment_size_sec: 3.
  hop_size_sec: 1.5
  device: "cuda:0"
  show_progressbar: True
  slice_audio_for_debug: False
  pass_through_ch0: False
  mc_mvdr: True
  mc_mask_floor_db: 0.  # for MC, MVDR without any direct masking worked best
  sc_mask_floor_db: -inf  # for SC, direct masking without floor worked best
  activity_th: 0.3

diarization:
  method: 'word_nmesc'     # choose from "word_nmesc", "nmesc" and "nmesc_msdd"
  min_embedding_windows: [3.0,2.5,2.0,1.5,1.0,0.5]
  embedding_model_name: "titanet_large"
  msdd_model_name: "diar_msdd_telephonic"
  # vad_model_name: "vad_telephony_marblenet"    # for 8kHz telephone
  vad_model_name: "vad_multilingual_marblenet"   # for 16kHz
  apply_deduplication: true

scoring:
  save_visualizations: False

## one MC session:
#session_query: 'device_name == "plaza_0" and is_mc == True and meeting_id == "MTG_30891"'

# one SC session:
#session_query: 'device_name == "plaza_0" and is_mc == False and meeting_id == "MTG_30891"'

# all sessions:
session_query: null
