# All paths are relative to the project root.
train_dir: sample_data/css_train_set
val_dir: sample_data/css_train_set  # same as train_dir for debug purposes only!
out_dir: outputs/css_train

single_channel: True
conformer_css_cfg:
  extractor_conf:
    ipd_index: ''  # instead of 1,0;2,0;3,0;4,0;5,0;6,0 for MC
  nnet_conf:
    in_features: 257  # instead of 1799 for MC

train_set_cfg:
  sample_frac: 1.0
  max_urls: 2  # null means no limit
val_set_cfg:
  sample_frac: 1.0
  max_urls: 2  # null means no limit

clip_gt_to_mixture: True

log_params_mlflow: False
log_metrics_mlflow: False

scheduler_step_every: [1, iterations]
scheduler_name: linear_warmup_decay
scheduler_linear_warmup_decay_cfg:
  warmup: 30
  decay: 60
stop_after: [90, iterations]

eval_every: [30, iterations]

global_batch_size: 32
learning_rate: 1e-4
weight_decay: 1e-2  # according to the paper set to 1e-2

is_debug: true